.TH "__request" 3 "27 Jan 2013" "Version 0.1" "usb-control" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__request \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "gchar * \fBuser\fP"
.br
.RI "\fIUser which connected the device. \fP"
.ti -1c
.RI "const gchar * \fBserial\fP"
.br
.RI "\fISerial of the device. \fP"
.ti -1c
.RI "const gchar * \fBdevtype\fP"
.br
.RI "\fIdevice's devtype \fP"
.ti -1c
.RI "gboolean \fBauthorized\fP"
.br
.RI "\fIeither is authorized or no. \fP"
.ti -1c
.RI "gchar * \fBdate\fP"
.br
.RI "\fIcurrent date of the system. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for usb-control from the source code.
