.TH "DEV" 3 "27 Jan 2013" "Version 0.1" "usb-gui" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEV \- 
.PP
A device.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb-gui.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const gchar * \fBidentifier\fP"
.br
.RI "\fIname that it identify \fP"
.ti -1c
.RI "const gchar * \fBserial\fP"
.br
.RI "\fIdevice's serial number \fP"
.in -1c
.SH "Detailed Description"
.PP 
A device. 

.SH "Author"
.PP 
Generated automatically by Doxygen for usb-gui from the source code.
